### ISSUE TITLE
How should themes and site variables be integrated?

### ISSUE THREAD

**Issue by oliverlloyd** [nooitaf/meteor-semantic-ui#27]
I'd really like to use these features - it's stuff like this that makes Semantic so great - but it's not clear how this should work with Meteor.

Clearly the src file needs to exist somewhere but when I tried adding it I couldn't make Semantic pick up my config changes.

If you have an idea how this should be done and could find the time to add an example that would be amazing.

**Comment by williamkhshea** [comment]
I'm just wondering if there is any timeline for it?

**Comment by javoire** [comment]
+1

**Comment by Maxpain177** [comment]
+1

**Comment by dmalik** [comment]
FYI - Stumbled across an issue using the src folder method. Modals and other modules relying on [transition](http://semantic-ui.com/modules/transition.html) were not working for me. The culprit turned out to be not using autoprefixer. The solution was to remove the less meteor package and add the [lauricio:less-autoprefixer](https://atmospherejs.com/lauricio/less-autoprefixer) package.

**Comment by nooitaf** [comment]
Great info @dmalik, thanks for sharing :)

**Comment by MattiSG** [comment]
+1

**Comment by flemay** [comment]
@dmalik Does the package **lauricio:less-autoprefixer** work well for you? I tried it with a basic meteor app (meteor create appname) and it does not work. I described the issue [here](https://github.com/Lauricio/less-autoprefixer/issues/2).

Thanks!

**Comment by iSuslov** [comment]
This is unacceptable! I spend almost an hour trying to customize it. Please, put a BIG warning that you DON'T support customizing in meteor. And remove this section from documentation on atmosphere. Seriously, for what I should know that there is a folder "/site" and it is EDITABLE. But it does not work! WTF!?

**Comment by nooitaf** [comment]
@iSuslov wrong repo?
